# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\client_chat.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(547, 313)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sendBtn = QtWidgets.QPushButton(self.centralwidget)
        self.sendBtn.setGeometry(QtCore.QRect(470, 260, 61, 31))
        self.sendBtn.setObjectName("sendBtn")
        self.msgEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.msgEdit.setGeometry(QtCore.QRect(200, 260, 261, 31))
        self.msgEdit.setObjectName("msgEdit")
        self.contactsView = QtWidgets.QListView(self.centralwidget)
        self.contactsView.setGeometry(QtCore.QRect(20, 20, 161, 271))
        self.contactsView.setObjectName("contactsView")
        self.chatView = QtWidgets.QListWidget(self.centralwidget)
        self.chatView.setGeometry(QtCore.QRect(200, 20, 331, 231))
        self.chatView.setObjectName("chatView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.sendBtn.setText(_translate("MainWindow", "Send"))
