"""update

Revision ID: 68219838079e
Revises: 946a76411282
Create Date: 2021-12-25 12:58:33.835378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68219838079e'
down_revision = '946a76411282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_history', sa.Column('time', sa.DateTime(), nullable=True))
    op.drop_column('message_history', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_history', sa.Column('author', sa.VARCHAR(), nullable=True))
    op.drop_column('message_history', 'time')
    # ### end Alembic commands ###
