"""update

Revision ID: 225ae8d1bb3b
Revises: 68219838079e
Create Date: 2021-12-25 13:17:10.144743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '225ae8d1bb3b'
down_revision = '68219838079e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
