"""update

Revision ID: 946a76411282
Revises: 109535f4316b
Create Date: 2021-12-25 12:44:00.602015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '946a76411282'
down_revision = '109535f4316b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_history', sa.Column('author', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message_history', 'author')
    # ### end Alembic commands ###
