"""update

Revision ID: ada712f53d9b
Revises: f301db52117a
Create Date: 2021-12-14 19:12:57.012101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ada712f53d9b'
down_revision = 'f301db52117a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
